import { computed, defineComponent, h } from 'vue'
import { flushPromises, shallowMount } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import { beforeEach, describe, expect, it, vi } from 'vitest'
const api = vi.hoisted(() => ({ querySyncTasks: vi.fn(), queryExternalSystems: vi.fn(), queryInterfaceDefinitions: vi.fn(), listSyncConsumers: vi.fn(), getSyncTaskForEdit: vi.fn(), createSyncTask: vi.fn(), updateSyncTask: vi.fn(), createSyncTaskVersion: vi.fn(), enableSyncTask: vi.fn(), disableSyncTask: vi.fn() }))
const tableApi = vi.hoisted(() => ({ queryTableByCode: vi.fn() }))
const buttons = vi.hoisted(() => ({ top: [{ id: 1, name: '新增', event_action: 'create' }], line: [{ id: 2, name: '详情', event_action: 'detail' }, { id: 3, name: '编辑', event_action: 'update' }, { id: 4, name: '创建版本', event_action: 'create_version' }, { id: 5, name: '启用', event_action: 'enable' }, { id: 6, name: '停用', event_action: 'disable' }] }))
vi.mock('quasar', () => ({ useQuasar: () => ({ screen: { lt: { md: false } } }) })); vi.mock('boot/axios', () => ({ instance: {} })); vi.mock('src/api/services/integration', () => ({ useIntegrationApi: () => api })); vi.mock('src/api/services/sys-table', () => ({ useTableApi: () => tableApi })); vi.mock('src/composables/page-buttons', () => ({ usePageButtons: () => ({ top_buttons: computed(() => buttons.top), line_buttons: computed(() => buttons.line), has_line_buttons: computed(() => true) }) })); vi.mock('src/composables/confirm-dialog', () => ({ useConfirmDialog: () => ({ confirmAction: () => ({ onOk: vi.fn() }) }) })); vi.mock('src/components/BaseContent/BaseContent.vue', () => ({ default: { template: '<div><slot /></div>' } })); vi.mock('src/components/Table/TablePagination.vue', () => ({ default: { template: '<div />' } })); vi.mock('src/components/Query/AdvancedQuery.vue', () => ({ default: { template: '<div />' } })); vi.mock('./SyncTaskFormDialog.vue', () => ({ default: { template: '<div />' } })); vi.mock('./SyncTaskDetailDialog.vue', () => ({ default: { template: '<div />' } }))
import Page from './Index.vue'
const Slot = defineComponent({ setup(_, { slots }) { return () => h('div', slots.default?.()) } }); const Table = defineComponent({ props: { rows: Array }, setup(props, { slots }) { return () => h('div', { 'data-count': props.rows?.length }, [slots.top?.(), slots.bottom?.()]) } })
const row = { id: 1, task_code: 'employee_sync', task_name: '人员同步', version: 1, status: 'draft', external_system: { id: 1, code: 'hr', name: 'HR' }, interface_definition: { id: 2, code: 'employee', name: '人员', version: 1 }, consumer: { code: 'org_employee', name: '', version: 1 }, schedule_type: 'none', timezone: 'UTC', checkpoint_mode: 'timestamp', lookback_seconds: 0, window_slice_seconds: 3600, input_plan_summary: { version: 1, static_parameter_count: 0, has_window_bindings: true }, revision: 1, gmt_modify: '' } as const
describe('sync task page permissions', () => {
  beforeEach(() => { setActivePinia(createPinia()); Object.values(api).forEach((mock) => mock.mockReset()); api.querySyncTasks.mockResolvedValue({ data: [row], total: 1 }); api.queryExternalSystems.mockResolvedValue({ data: [] }); api.queryInterfaceDefinitions.mockResolvedValue({ data: [] }); api.listSyncConsumers.mockResolvedValue({ data: [] }); tableApi.queryTableByCode.mockResolvedValue({ data: { table_fields: [] } }) })
  it('loads metadata and applies state-specific dynamic buttons without run or cancel', async () => {
    const wrapper = shallowMount(Page, { global: { plugins: [createPinia()], stubs: { BaseContent: Slot, QTable: Table, QInput: true, QSelect: true, QBtn: true, QIcon: true, QChip: true, QTd: Slot, QTooltip: true, QSpace: true, TablePagination: true, AdvancedQuery: true, SyncTaskFormDialog: true, SyncTaskDetailDialog: true } } }); await flushPromises()
    expect(tableApi.queryTableByCode).toHaveBeenCalledWith('integration_sync_task'); expect(api.querySyncTasks).toHaveBeenCalled()
    const vm = wrapper.vm as unknown as { availableLineButtons: (value: typeof row) => Array<{ event_action: string }> }
    expect(vm.availableLineButtons(row).map((item) => item.event_action)).toEqual(['detail', 'update', 'enable'])
    expect(buttons.line.map((item) => item.event_action)).not.toEqual(expect.arrayContaining(['run', 'cancel', 'checkpoint']))
  })
})
